name: Build Executables

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build Windows executable
      run: |
        pyinstaller --onefile --name="Game" --add-data "Assets;Assets" main.py

    - name: Upload Windows executable artifact
      uses: actions/upload-artifact@v2
      with:
        name: Windows-Build
        path: dist/Game.exe

  build-linux:
    runs-on: ubuntu-latest
          
    container:
      image: mygame:latest
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Build Linux executable
      run: |
        # The Docker container will run this command defined in the Dockerfile
        
    - name: Upload Linux executable artifact
      uses: actions/upload-artifact@v2
      with:
        name: Linux-Build
        path: dist/Game
        